
services:
  postgres:
    image: postgres:latest
    container_name: attractions_db
    restart: always # запуск контейнера при старте Docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attractions_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: