
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: landmarkly_app
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/attractions_db
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
        - SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/db.changelog-master.xml
  postgres:
    image: postgres:latest
    container_name: attractions_db
    restart: always # запуск контейнера при старте Docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attractions_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: