version: '3.8'

services:
  app:
    build: .
    container_name: landmarkly-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/landmark_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - landmarkly-network

  postgres:
    image: postgres:15-alpine3.17
    container_name: landmarkly-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=landmark_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - landmarkly-network

networks:
  landmarkly-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local