spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/landmarkly_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  feign:
    client:
      config:
        default:
          loggerLevel: full
          decode404: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
